name: CI CD Artefaktai

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Kodo patikra
      - name: Checkout code
        uses: actions/checkout@v3

      # Idiegti phytona
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      # Lintas(flake8)
      - name: Run flake8 linter
        run: |
          flake8 app.py

      # Testai
      - name: Run tests with pytest
        run: |
          pytest
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: lint-and-test  # Turi praeiti lint ir test joba
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Prisijungia prie Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Buildina image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/pythonapp:latest .

      # Pushina image i dockerhuba
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/pythonapp:latest 
